CREATE TABLE MEMBER (
  ID_MEMBER INT NOT NULL PRIMARY KEY,
  USERNAME VARCHAR(50) NOT NULL,
  GENDER VARCHAR(10) NOT NULL,
  SKINTYPE VARCHAR(20) NOT NULL,
  SKINCOLOR VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_MEMBER_REVIEW_PRODUCT FOREIGN KEY (ID_MEMBER) REFERENCES REVIEW_PRODUCT(ID_MEMBER) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_MEMBER_LIKE_REVIEW FOREIGN KEY (ID_MEMBER) REFERENCES LIKE_REVIEW(ID_MEMBER) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PRODUCT (
  ID_PRODUCT INT NOT NULL PRIMARY KEY,
  NAME_PRODUCT VARCHAR(50) NOT NULL,
  PRICE DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_PRODUCT_REVIEW_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES REVIEW_PRODUCT(ID_PRODUCT) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE REVIEW_PRODUCT (
  ID_REVIEW INT NOT NULL PRIMARY KEY,
  ID_PRODUCT INT NOT NULL,
  ID_MEMBER INT NOT NULL,
  DESC_REVIEW VARCHAR(500) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_REVIEW_PRODUCT_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_REVIEW_PRODUCT_MEMBER FOREIGN KEY (ID_MEMBER) REFERENCES MEMBER(ID_MEMBER) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_REVIEW_PRODUCT_LIKE_REVIEW FOREIGN KEY (ID_REVIEW) REFERENCES LIKE_REVIEW(ID_REVIEW) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LIKE_REVIEW (
  ID_REVIEW INT NOT NULL,
  ID_MEMBER INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_LIKE_REVIEW_REVIEW_PRODUCT FOREIGN KEY (ID_REVIEW) REFERENCES REVIEW_PRODUCT(ID_REVIEW) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_LIKE_REVIEW_MEMBER FOREIGN KEY (ID_MEMBER) REFERENCES MEMBER(ID_MEMBER) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY (ID_REVIEW, ID_MEMBER)
);
